### ISSUE TITLE
How can i debug the html5Uploader ?

### ISSUE THREAD

**Issue by samhk222** [MicheleBertoli/jquery-html5-uploader#3]
I want to debug the information .... also, how can i retrieve information to use in other parts of form ?

```
    onSuccess : function(){
      console.log(html5Uploader); ???????
      $('#ven_pendencias_arquivos_id').val(ret.last_id); ????????
    }
```

**Comment by MicheleBertoli** [comment]
Hello @samhk222,

the [onSuccess](https://github.com/MicheleBertoli/jquery-html5-uploader/blob/master/jquery.html5uploader.js#L127) callback has 3 parameters, the third one is the server response.

You can do something like:

``` javascript
onSuccess: function(e, file, response) {
  console.log(response);
}
```

Hope this helps.

**Comment by samhk222** [comment]
Man, this is the best plugin ever!
Thank you very much!
